spring:
  application:
    name: taskflow
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

jwt:
  secret: mySecretKeymySecretKeymySecretKey